# Configuration for companies_house_ocr_runner
# Default location ~/config/ch_ocr_runner_config.yml

DATA_DIR: /path/to/data/dir

# Directory which holds all the PDF files
PDF_DIR: /path/to/pdf/dir

# Directory for the ocr runner to store intermediate files (image files etc.)
WORKING_DIR: /path/to/working/dir

# The batch allocation file is used
# to look up which PDFs are allocated to this machine
WORK_BATCH_ALLOCATION_FILEPATH: /path/to/batch/allocation/csv